language: scala
scala:
- 2.11.2
script:
- sbt ++$TRAVIS_SCALA_VERSION "test" "publishOnlyWhenOnMaster"
jdk:
- oraclejdk8
env:
  global:
  - SCALAMETA_MAVEN_REALM="Sonatype Nexus Repository Manager"
  - SCALAMETA_MAVEN_DOMAIN="oss.sonatype.org"
  - secure: RFwke785jakvgLUvSdmgJ4v/z5UT2MmbtpcP6FXxRiIGc/qmQe66plB4ODJy4fnZqI9weBbMBV3G/wLQe/oHJg4877GBqON7ARgVNOxyLiRcVySe3ik6o1QUSUNsemFQSlXQMPfnz1g29Lx1xK8hpAzvycDMTgCHwr4oY7W0G3k=
  - secure: fKtvF3KG1xjXSPF+6c+L8nNtP8pf8C0+/70YE89sYkWHN9/fK3FQHlzOm3mSg9eti+g/gs/feIg35FJ2nX8YzpyWq7vLpeXkG4q98/pb/J3kLsXbeeoq3MrDb1wh1If5D12KVrA8Z4WEeUlkWUCQ+emYQJl5M1h/KfGhIMYsNIc=
