language: scala

scala:
- 2.11.2

jdk:
- oraclejdk8

env:
  global:
  - SCALAMETA_MAVEN_REALM="Sonatype Nexus Repository Manager"
  - SCALAMETA_MAVEN_DOMAIN="oss.sonatype.org"
  - secure: V2XX4rj+sW+f1KIFhft43tnrEYXIkStB+OCo5cp9bkokF8S/8onfRM7VhlUbHvgwzwSkKfVAZl33tOUh750L7epuWKJnD2VvonPbyfY9sri32Xzi/5UWVffr4u3vvEYQESuF7Vgfi0P6BkG8wD/wuqjNcpFQniXWPFIW/qaQgItku5rR89UHF4o+YCrsoTr+qt96kjdfSzWcbMCcun+4oxjVzUBgGsUxC1/dF+qDtFEfLsQtIybIfeY6lOhETP51gX/JBo37IApZ+pun+JO3zRZYnz2ebsSCUREieaEvveFZBaXoYWzUryuN0y7Zre6AnP4bdCtoGTRlkU4VXbh6Yk0VamNta7FeqPCN4oVq/cr9WHzpijG60LqfDy5Y/akTOUASpFizx4oEg8ssQI0kJMJY8+uumwExhBLLGLtzDjkKCjfXoX6VYxhksrHq1EmLEK1o8c83MIIZERqK4WRQasIGX2o8eM/1l40dnyF2gGCYsa8L6mkAPlnPxYu5xADUOwSKllnn553zaOaDP62PyN3GxvtFvjzt4NRxyJdyWaVckKr7VdFXX3rAkkgE4TgEI7ewCMJnjdJCNnxC1y43yf3Ehd/+5GDU3Iq9tFupaOHU1I6FJJ0l6unXD1/9fulftNIKiw8mk2iMSaT7es48UTFdwxW/J9HnrfjVITkdpmQ=
  - secure: YoNnXBdRVySRgRacEYke3wDH9MqYovuLTlyzrTBhl+R9sbU/IXearKDhOx7PQgawefiuYrhHpqqEqzhlWtluYdMTnua0S/q9YWzk2TrH3ynZK1bQzBJySV59cEedJS3iF0sfcDJvkp9L4uax7wA88zUMZTTvsZ2ZxaXho6RnZDWQtGgyN9nZ98LsnQAzADynva9sFEV20vYNKEFkevar7BgHfPgSE57IeigCMS2maku5SPPsq6+Ao3SgKn+4H1VJEikk2r0cvHyDIiJ+lUaE1BSmNqCneL2/iD3LkjER5FGS7+NnvENc/Aj0AtfyE3y3sm8lgMhfXVjDodnm1M6gF4xP6JyCbuTUCkXxK2CSjWzBXd9fbQnsCO4pm6zjbZ4820i/58oxyGogYle5Thp6Aisp7JbMwfnzIx1EKM2uipOIaLkc0xD0mxq1HEezjgHlOczmBlzWFJ2FyEflGP9CXCSHZD4WiWNPeC/Tt7m+zIgx+9dUAnSwlgPtBdRdrkyhe9PfCjiJCKEZNmuEGxb7Hb4S2X7vjrpuNsJAIB36mJfCRGkB8O5F6VFbIgrIahZWpnEOW616ppUbOP6ud5KUtEyBT+E71CPZqAN0kDVAMbwQ+uUbllvX0CC4PVFH8wkNIlCKvw4rHFqQ1Hbfu/Qt9qeGi0cSaNmbt/uZqbJMlOU=

after_success:
  - sbt publishOnlyWhenOnMaster
